export namespace UseFetchConsts {
  const TOTAL_RETRIES_DURATION = 2500;
  export const DEFAULT_MAX_FETCH_RETRY = 5;
  export const DEFAULT_DELAY_BEFORE_EACH_RETRY = TOTAL_RETRIES_DURATION / DEFAULT_MAX_FETCH_RETRY;
}

export const FORCE_UPDATE_STATE_LIMIT_TO_AVOID_HUGE_NUMBER_IN_RAM = 99;
